<a href="https://colab.research.google.com/github/Sru-j/daily_lab_activities/blob/main/data_loading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
DIR = '/content/drive/My Drive/Colab Notebooks/data'
datafile ='auth_logs.csv'
filename = DIR+'/'+datafile

In [ ]:
import os
os.chdir(DIR)

In [ ]:
!ls
!pwd

drive  sample_data
/content

In [ ]:
import pandas as pd
df = pd.read_csv(filename)
df

               timestamp username          ip   status   role    country
0    2026-01-05 09:00:10   walter  10.0.0.104  SUCCESS  admin    Germany
1    2026-01-05 09:00:31   victor  10.0.0.128  SUCCESS   user        USA
2    2026-01-05 09:01:00  charlie  10.0.0.162  SUCCESS   user        USA
3    2026-01-05 09:01:34    trent   10.0.0.99  SUCCESS   user        UAE
4    2026-01-05 09:02:03   victor  10.0.0.222   FAILED   user        USA
..                   ...      ...         ...      ...    ...        ...
115  2026-01-05 09:57:38   walter  10.0.0.208   FAILED   user  Australia
116  2026-01-05 09:58:08    trent  10.0.0.213   FAILED   user  Singapore
117  2026-01-05 09:58:34      bob   10.0.0.73   FAILED   user  Australia
118  2026-01-05 09:59:09   walter  10.0.0.158  SUCCESS   user  Australia
119  2026-01-05 09:59:36  mallory   10.0.0.48  SUCCESS   user        UAE

[120 rows x 6 columns]

In [ ]:
df.columns

Index(['timestamp', 'username', 'ip', 'status', 'role', 'country'], dtype='object')

In [ ]:
df.dtypes

timestamp    object
username     object
ip           object
status       object
role         object
country      object
dtype: object

In [ ]:
df.describe()

                  timestamp username          ip   status  role country
count                   120      120         120      120   120     120
unique                  120       12          92        2     2       8
top     2026-01-05 09:00:10    alice  10.0.0.223  SUCCESS  user     USA
freq                      1       13           4       88   100      22

In [ ]:
#read tsv file
DIR = '/content/drive/My Drive/Colab Notebooks/data'
datafile ='dns_queries.tsv'
filename = DIR+'/'+datafile
df = pd.read_csv(filename, sep='\t')
df

,timestamp,src_ip,query,qtype,rcode,answer_count
0,2026-01-05 09:00:10,10.0.0.89,evil.example,MX,SERVFAIL,2
1,2026-01-05 09:00:31,10.0.0.144,example.com,MX,NOERROR,0
2,2026-01-05 09:01:00,10.0.0.63,updates.vendor,TXT,SERVFAIL,1
3,2026-01-05 09:01:34,10.0.0.178,mail.example,TXT,NXDOMAIN,0
4,2026-01-05 09:02:03,10.0.0.25,evil.example,AAAA,NXDOMAIN,1
...,...,...,...,...,...,...
115,2026-01-05 09:57:38,10.0.0.119,example.com,A,NXDOMAIN,3
116,2026-01-05 09:58:08,10.0.0.111,msis.edu,TXT,SERVFAIL,3
117,2026-01-05 09:58:34,10.0.0.20,msis.edu,CNAME,SERVFAIL,1
118,2026-01-05 09:59:09,10.0.0.18,github.com,CNAME,SERVFAIL,2
119,2026-01-05 09:59:36,10.0.0.99,evil.example,TXT,SERVFAIL,3

In [ ]:
#read xml file
DIR = '/content/drive/My Drive/Colab Notebooks/data'
datafile ='ioc_feed.xml'
filename = DIR+'/'+datafile
df = pd.read_xml(filename)
df

            type                                              value confidence
0            url                         http://phish.example/login        low
1         domain                                      phish.example       high
2    hash_sha256  b0b46f95f121770f0a64a5a10443b2bc3a9a45dfa5b75c...        low
3             ip                                         10.0.0.212       high
4    hash_sha256  e08672b8301ced5dfcbc3f75e2190a832a5c522af0d5d5...     medium
..           ...                                                ...        ...
115          url                            http://mal.example/drop        low
116       domain                                     badcdn.example       high
117           ip                                         10.0.0.144     medium
118           ip                                          10.0.0.50     medium
119          url                            http://mal.example/drop     medium

[120 rows x 3 columns]

In [ ]:
#read json file
DIR = '/content/drive/My Drive/Colab Notebooks/data'
datafile ='superstore_json.json'
filename = DIR+'/'+datafile
df = pd.read_json(filename)
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,05-04-2017,05-09-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
#read excel file
DIR = '/content/drive/My Drive/Colab Notebooks/data'
datafile ='soc_alerts.xlsx'
filename = DIR+'/'+datafile
df = pd.read_excel(filename)
df

,timestamp,tool,event_type,severity,src_ip,dest,message
0,2026-01-05T09:00:10Z,Defender,XSS,medium,10.0.0.27,/upload,Suspicious process behavior
1,2026-01-05T09:00:31Z,EDR,SuspiciousLogin,high,10.0.0.229,/settings,Suspicious process behavior
2,2026-01-05T09:01:00Z,Defender,XSS,high,10.0.0.108,/upload,Known bad indicator matched
3,2026-01-05T09:01:34Z,IDS,PrivilegeEscalation,medium,10.0.0.172,/settings,Anomalous request pattern detected
4,2026-01-05T09:02:03Z,WAF,XSS,critical,10.0.0.25,/admin,Known bad indicator matched
...,...,...,...,...,...,...,...
115,2026-01-05T09:57:38Z,IDS,DataExfil,medium,10.0.0.33,/api/v1/profile,Anomalous request pattern detected
116,2026-01-05T09:58:08Z,IDS,SuspiciousLogin,critical,10.0.0.14,/api/v1/orders,Multiple failed login attempts observed
117,2026-01-05T09:58:34Z,IDS,PrivilegeEscalation,medium,10.0.0.210,/api/v1/profile,Suspicious process behavior
118,2026-01-05T09:59:09Z,SIEM,DataExfil,high,10.0.0.133,/settings,Anomalous request pattern detected
119,2026-01-05T09:59:36Z,SIEM,DataExfil,medium,10.0.0.25,/api/v1/orders,Unusual API usage detected

In [ ]:
#read jsonl file
DIR = '/content/drive/My Drive/Colab Notebooks/data'
datafile ='netflow.jsonl'
filename = DIR+'/'+datafile
df = pd.read_json(filename,lines='true')
df

,timestamp,src_ip,dst_ip,dst_port,proto,bytes,packets,action
0,2026-01-05 09:00:10+00:00,10.0.0.92,10.0.0.14,22,UDP,8208,39,DENY
1,2026-01-05 09:00:31+00:00,10.0.0.75,10.0.0.139,22,TCP,7160,9,ALLOW
2,2026-01-05 09:01:00+00:00,10.0.0.188,10.0.0.95,25,UDP,6095,3,DENY
3,2026-01-05 09:01:34+00:00,10.0.0.15,10.0.0.147,3389,TCP,6039,36,ALLOW
4,2026-01-05 09:02:03+00:00,10.0.0.20,10.0.0.100,3389,UDP,12623,36,ALLOW
...,...,...,...,...,...,...,...,...
115,2026-01-05 09:57:38+00:00,10.0.0.112,10.0.0.116,3389,UDP,1792,2,ALLOW
116,2026-01-05 09:58:08+00:00,10.0.0.92,10.0.0.143,22,UDP,14251,25,ALLOW
117,2026-01-05 09:58:34+00:00,10.0.0.76,10.0.0.107,53,TCP,11975,36,ALLOW
118,2026-01-05 09:59:09+00:00,10.0.0.148,10.0.0.135,80,UDP,2877,9,ALLOW
119,2026-01-05 09:59:36+00:00,10.0.0.79,10.0.0.70,53,TCP,1136,11,DENY

In [ ]:
#read txt file
DIR = '/content/drive/My Drive/Colab Notebooks/data'
datafile ='superstore.txt'
filename = DIR+'/'+datafile
df = pd.read_csv(filename,sep='\t')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,05-04-2017,05-09-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
#read log file
DIR = '/content/drive/My Drive/Colab Notebooks/data'
datafile ='web_access.log'
filename = DIR+'/'+datafile
df = pd.read_csv(filename,sep=' ')
df

,2026-01-05T09:00:10Z,10.0.0.72,DELETE,/reset,403,830,python-requests/2.31
0,2026-01-05T09:00:31Z,10.0.0.66,POST,/settings,500,1801,PostmanRuntime/7.35
1,2026-01-05T09:01:00Z,10.0.0.29,POST,/reset,200,3441,python-requests/2.31
2,2026-01-05T09:01:34Z,10.0.0.217,DELETE,/search,403,2942,PostmanRuntime/7.35
3,2026-01-05T09:02:03Z,10.0.0.210,POST,/reset,400,1845,PostmanRuntime/7.35
4,2026-01-05T09:02:33Z,10.0.0.82,POST,/upload,400,2587,PostmanRuntime/7.35
...,...,...,...,...,...,...,...
114,2026-01-05T09:57:38Z,10.0.0.243,DELETE,/login,200,4901,PostmanRuntime/7.35
115,2026-01-05T09:58:08Z,10.0.0.212,DELETE,/settings,200,3335,PostmanRuntime/7.35
116,2026-01-05T09:58:34Z,10.0.0.46,PUT,/api/v1/orders,200,2452,python-requests/2.31
117,2026-01-05T09:59:09Z,10.0.0.116,POST,/login,500,2213,python-requests/2.31
118,2026-01-05T09:59:36Z,10.0.0.129,DELETE,/settings,200,918,python-requests/2.31

In [ ]:
!pip install dbfread

Requirement already satisfied: dbfread in /usr/local/lib/python3.12/dist-packages (2.0.7)

In [ ]:
#read dbf file
from dbfread import DBF

dbf = DBF('/content/drive/My Drive/Colab Notebooks/data/superstore.dbf',encoding='latin-1')
df = pd.DataFrame(dbf)
df

,N___ROW_ID,ORDER_ID,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_I,CUSTOMER_N,SEGMENT,COUNTRY,CITY,...,POSTAL_COD,REGION,PRODUCT_ID,CATEGORY,SUB_CATEGO,PRODUCT_NA,SALES,QUANTITY,DISCOUNT,PROFIT
0,1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,272,CA-2015-155334,7/30/2015,7/31/2015,First Class,HA-14920,Helen Andreada,Consumer,United States,San Francisco,...,94109,West,TEC-AC-10003628,Technology,Accessories,Logitech 910-002974 M325 Wireless Mouse for We...,209.9300,7,0.00,92.3692
272,273,CA-2015-155334,7/30/2015,7/31/2015,First Class,HA-14920,Helen Andreada,Consumer,United States,San Francisco,...,94109,West,FUR-FU-10003274,Furniture,Furnishings,Regeneration Desk Collection,5.2800,3,0.00,2.3232
273,274,CA-2015-155334,7/30/2015,7/31/2015,First Class,HA-14920,Helen Andreada,Consumer,United States,San Francisco,...,94109,West,OFF-BI-10002557,Office Supplies,Binders,Presstex Flexible Ring Binders,10.9200,3,0.20,4.0950
274,275,CA-2017-118136,9/16/2017,9/17/2017,First Class,BB-10990,Barry Blumstein,Corporate,United States,Inglewood,...,90301,West,OFF-PA-10002615,Office Supplies,Paper,"Ampad Gold Fibre Wirebound Steno Books, 6"" x 9...",8.8200,2,0.00,4.0572
275,276,CA-2017-118136,9/16/2017,9/17/2017,First Class,BB-10990,Barry Blumstein,Corporate,United States,Inglewood,...,90301,West,OFF-AR-10001427,Office Supplies,Art,Newell 330,5.9800,1,0.00,1.5548

In [ ]:
#read sql file
DIR = '/content/drive/My Drive/Colab Notebooks/data'
datafile ='soc_dump.sql'
filename = DIR+'/'+datafile
with open(filename, 'r') as f:
  sql_content = f.read()

print(df)
df.shape

     N___ROW_ID        ORDER_ID  ORDER_DATE   SHIP_DATE       SHIP_MODE  \
0             1  CA-2016-152156  11-08-2016  11-11-2016    Second Class
1             2  CA-2016-152156  11-08-2016  11-11-2016    Second Class
2             3  CA-2016-138688  06-12-2016   6/16/2016    Second Class
3             4  US-2015-108966  10-11-2015  10/18/2015  Standard Class
4             5  US-2015-108966  10-11-2015  10/18/2015  Standard Class
..          ...             ...         ...         ...             ...
271         272  CA-2015-155334   7/30/2015   7/31/2015     First Class
272         273  CA-2015-155334   7/30/2015   7/31/2015     First Class
273         274  CA-2015-155334   7/30/2015   7/31/2015     First Class
274         275  CA-2017-118136   9/16/2017   9/17/2017     First Class
275         276  CA-2017-118136   9/16/2017   9/17/2017     First Class

    CUSTOMER_I       CUSTOMER_N    SEGMENT        COUNTRY             CITY  \
0     CG-12520      Claire Gute   Consumer  United States        Henderson
1     CG-12520      Claire Gute   Consumer  United States        Henderson
2     DV-13045  Darrin Van Huff  Corporate  United States      Los Angeles
3     SO-20335   Sean O'Donnell   Consumer  United States  Fort Lauderdale
4     SO-20335   Sean O'Donnell   Consumer  United States  Fort Lauderdale
..         ...              ...        ...            ...              ...
271   HA-14920   Helen Andreada   Consumer  United States    San Francisco
272   HA-14920   Helen Andreada   Consumer  United States    San Francisco
273   HA-14920   Helen Andreada   Consumer  United States    San Francisco
274   BB-10990  Barry Blumstein  Corporate  United States        Inglewood
275   BB-10990  Barry Blumstein  Corporate  United States        Inglewood

     ... POSTAL_COD  REGION       PRODUCT_ID         CATEGORY   SUB_CATEGO  \
0    ...      42420   South  FUR-BO-10001798        Furniture    Bookcases
1    ...      42420   South  FUR-CH-10000454        Furniture       Chairs
2    ...      90036    West  OFF-LA-10000240  Office Supplies       Labels
3    ...      33311   South  FUR-TA-10000577        Furniture       Tables
4    ...      33311   South  OFF-ST-10000760  Office Supplies      Storage
..   ...        ...     ...              ...              ...          ...
271  ...      94109    West  TEC-AC-10003628       Technology  Accessories
272  ...      94109    West  FUR-FU-10003274        Furniture  Furnishings
273  ...      94109    West  OFF-BI-10002557  Office Supplies      Binders
274  ...      90301    West  OFF-PA-10002615  Office Supplies        Paper
275  ...      90301    West  OFF-AR-10001427  Office Supplies          Art

                                            PRODUCT_NA     SALES  QUANTITY  \
0                    Bush Somerset Collection Bookcase  261.9600         2
1    Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2    Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3        Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                       Eldon Fold 'N Roll Cart System   22.3680         2
..                                                 ...       ...       ...
271  Logitech 910-002974 M325 Wireless Mouse for We...  209.9300         7
272                       Regeneration Desk Collection    5.2800         3
273                     Presstex Flexible Ring Binders   10.9200         3
274  Ampad Gold Fibre Wirebound Steno Books, 6" x 9...    8.8200         2
275                                         Newell 330    5.9800         1

     DISCOUNT    PROFIT
0        0.00   41.9136
1        0.00  219.5820
2        0.00    6.8714
3        0.45 -383.0310
4        0.20    2.5164
..        ...       ...
271      0.00   92.3692
272      0.00    2.3232
273      0.20    4.0950
274      0.00    4.0572
275      0.00    1.5548

[276 rows x 21 columns]

(276, 21)

In [ ]:
#read yml file

import pandas as pd
from yaml import safe_load
from pandas import json_normalize

# 1. Define the path to your YAML file
file_path = '/content/drive/My Drive/Colab Notebooks/data/security_policy.yml'

# 2. Open the file and safely load the contents into a Python object
with open(file_path, 'r') as file:
    data = safe_load(file)

# 3. Convert the Python object (list/dict) to a DataFrame
# Use json_normalize for better handling of nested structures
df = json_normalize(data)

# 4. Display the resulting DataFrame
#print(df.head())
df.columns

Index(['policy.org', 'policy.environment', 'policy.generated_on',
       'policy.password_policy.min_length',
       'policy.password_policy.require_upper',
       'policy.password_policy.require_lower',
       'policy.password_policy.require_digit',
       'policy.password_policy.require_symbol', 'policy.mfa.enabled',
       'policy.mfa.methods', 'policy.network_controls.allowed_ports',
       'policy.network_controls.blocked_ports',
       'policy.logging.retention_days', 'policy.logging.sources'],
      dtype='object')